/////////////////////////////////////////
/////////////// LOCALHOST ///////////////
/////////////////////////////////////////

///////////////////////////////
//////////// USER /////////////
///////////////////////////////

### Get all users
GET http://localhost:3000/v1/user

### Get user by wallet_address
GET http://localhost:3000/v1/user/0x1dF6bE628F34a964AcFb695CD9F5417DBc95ff42

///////////////////////////////
//////// ORGANISATION /////////
///////////////////////////////

/////////////////////////////////////////
//////////////// RENDER /////////////////
/////////////////////////////////////////

### Get all users
GET https://chain-server-api.onrender.com/v1/user