/////////////////////////////////////////
/////////////// LOCALHOST ///////////////
/////////////////////////////////////////
###
GET http://localhost:3000/v1/user

/////////////////////////////////////////
/////////////// ONRENDER ////////////////
/////////////////////////////////////////
###
GET https://chain-server-api.onrender.com/v1/user